### ISSUE TITLE
Rectangle representation Wrong

### ISSUE THREAD

**Issue by invokesus** [sem6-project/grasp-detector#2]
Current rectangle representation has inadequate parameters(x,y,w,h) ie. a rectangle cannot be constructed with the given parameters. Ideas for better representation are required.

**Comment by himanshub16** [comment]
Method -1 : `(x, y, w, h, θ)`
   Catch : Trigonometric calculations in θ cause errors due to the cyclic behaviour of sin and cos.
Method - 2: `(x1, y1, x2, y2, x3, y3)`
   Catch : Rectangles drawn might not be accurate. However, they have to be approximately clear to be called a rectangle.

Currently using Method 2

**Comment by invokesus** [comment]
Noiiiiiiiiiice.

**Comment by invokesus** [comment]
But atan2 bruh
